### PR TITLE
Fix ldconfig parameters

### LINKED ISSUE #3: Fix ldconfig parameters
The dockerfile uses incorrect references to the Repast HPC dependencies' libraries.

Thanks to the contributions of @nietoga, who highlighted and contributed a fix to this issue.

### PR DESCRIPTION
**Pull request by nietoga**
image

### CODE REVIEW

**Comment by W-Mohammed** [comment]
Thanks, @nietoga, for your valued contribution.

**Review by W-Mohammed — APPROVED** [review]
Well spotted, thanks!

**Comment by nietoga** [comment]
You are welcome. Thanks for making the your Dockerfiles publicly available.

**Comment by nietoga** [comment]
@W-Mohammed  btw, you might need to fix this for the alpine version, too. I haven't tried that one yet, that's why I didn't bother.

And also, consider not removing `build-essential` modules as those are required to do compilations afterwards.

**Comment by W-Mohammed** [comment]
Thanks, @nietoga; I will:
- test the `alpine` version after making suggested changes, and,
- will edit the dockerfiles to keep the `build-essential`.

Thank you for the great suggestions.

**Comment by W-Mohammed** [comment]
HI @nietoga,

Do you mind testing the latest version of the `ubuntu` dockerfile or image? Since I was using the wrong libs' directories, but the containers still worked fine (based on the simple testing I carried out), I thought maybe `ldconfing` was unnecessary.

**Comment by nietoga** [comment]
I'll comment on the issue you opened for ldconfig.

**Pull request merged**
